version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo build step
      - run: mkdir build_output
      - run: touch build_output/complied_output.txt
      - persist_to_workspace:
          root: build_output
          paths:
            - '*'

  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/complied_output.txt

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo deploy step


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

### Ví dụ chạy song song
# version: 2

# jobs:
#   build-frontend:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo build-frontend step

#   build-backend:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo build-backend step

#   test-frontend:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo test-frontend step

#   test-backend:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo test-backend step

#   integration-tests:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo integration-tests step

#   deploy:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/repo
#     steps:
#       - run: echo deploy step

# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - build-frontend
#       - build-backend
#       - test-frontend:
#           requires:
#             - build-frontend
#       - test-backend:
#           requires:
#             - build-backend
#       - integration-tests:
#           requires:
#             - build-frontend
#             - build-backend
#       - deploy:
#           requires:
#             - test-frontend
#             - test-backend
#             - integration-tests
